### ISSUE TITLE
Getting undefined on search!

### ISSUE THREAD

**Issue by mgmgpyaesonewin** [Hitman666/GiphySearch_Vue2#1]
```
<template>
  <div class="hello">
    <input name="search" v-model="searchTerm">
    <button @click="performSearch">Search</button>
    <h1>{{ msg }}</h1>
  </div>
</template>
<script>
export default {
  name: 'HelloWorld',
  data() {
    return {
      msg: 'Welcome to GiphySearch',
      searchTerm: 'testing',
    };
  },
  methods: {
    performSearch: () => {
      console.log(this.searchTerm);
    },
  },
};
</script>
```

This console.log is getting undefined error. I don't know why.

**Comment by NikolaBreznjak** [comment]
The problem is on this line:

`performSearch: () => {`

you should write it like this:

`performSearch: function () {`

However, to be perfectly honest, I'm puzzled too, as I thought the `() =>` would get transpiled correctly. I even checked out with `npm run build` and opened the built code to see if the code is transpiled - it was, but still got the `undefined` msg in the console when I clicked on the button.

I'm going to check this on StackOverflow and update you on it. Thanks for raising this issue, as I'm also learning new things 💪

_edit_: I posted the question [here](https://stackoverflow.com/questions/49592204/cant-use-function-shorthand-syntax-in-vue-js).

**Comment by NikolaBreznjak** [comment]
You can find an explanation in [this answer](https://stackoverflow.com/questions/42971081/use-arrow-function-in-vue-computed-does-not-work). It comes down to the fact that an arrow function wouldn't bind `this` to the vue instance for which you are defining the computed property.
